build:
  image: php:latest
  commands:
    - sudo apt-get install git
    - curl -sS https://getcomposer.org/installer | php
    - ./composer.phar self-update
    - ./composer.phar install --quiet --prefer-dist
    - php -v
