build:
  image: php:latest
  privileged: true
  commands:
    - apt-get update && apt-get install git
    - curl -sS https://getcomposer.org/installer | php
    - ./composer.phar self-update
    - ./composer.phar install --prefer-dist
    - php -v
    - php vendor/bin/phpunit 
