sudo: false
language: php

php:
    - 7.0
    - 7.1
    - 5.6
    - nightly
env:
  - ISOLATED=true
  - ISOLATED=false
  - CLASSIC=true
  - CLASSIC=false
  
before_script:
    - composer self-update
    - composer install --no-interaction

script: ./vendor/bin/phpunit -c phpunit.xml
